#pragma once
#define PIN_TX0          21
#define PIN_RX0          20
#define PIN_TX1          0
#define PIN_RX1          1
#define PIN_SD_D0        11
#define PIN_SD_D1        10
#define PIN_SD_D2        15
#define PIN_SD_D3        14
#define PIN_SD_CLK       12
#define PIN_SD_CMD       13
#define PIN_SDA0         17
#define PIN_SCL0         18
#define PIN_LED          19
#define PIN_CAM_XCLK     23
#define PIN_CAM_D0       24
#define PIN_CAM_D1       25
#define PIN_CAM_D2       26
#define PIN_CAM_D3       27
#define PIN_CAM_HREF     28
#define PIN_CAM_VSYNC    29
#define PIN_CAM_PIXCLK   30
#define PIN_CAM_D4       31
#define PIN_CAM_D5       32
#define PIN_CAM_D6       33
#define PIN_CAM_D7       34